require:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  NewCops: disable
Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context']

Style/Documentation:
  Enabled: false

RSpec/FilePath:
  SpecSuffixOnly: true
